image:
  repository: omjaju18/ipl-voter
  tag: "184e4c8877a7c5e1bb50345ffcfe2dc565cc1e85"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 80
  targetPort: 5000     
  nodePort: 30007      

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

persistence:
  enabled: true
  size: 100Mi