apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ipl-voter
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ipl-voter
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s