apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ipl-voter.fullname" . }}
  labels:
    {{- include "ipl-voter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ipl-voter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ipl-voter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "ipl-voter.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: DB_PATH
              value: /data/votes.db
          volumeMounts:
            - name: votes-storage
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: votes-storage
          persistentVolumeClaim:
            claimName: {{ include "ipl-voter.fullname" . }}-pvc