apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ipl-voter.fullname" . }}-pvc
  labels:
    {{- include "ipl-voter.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi